# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
       mvn clean install -DskipTests
       org=<your org>
       repo=<your repo>
       workflow_ids=($(gh api repos/$org/$repo/actions/workflows | jq '.workflows[] | select(.["state"] | contains("disabled_manually")) | .id'))
       for workflow_id in "${workflow_ids[@]}"
       do
       echo "Listing runs for the workflow ID $workflow_id"
       run_ids=( $(gh api repos/$org/$repo/actions/workflows/$workflow_id/runs --paginate | jq '.workflow_runs[].id') )
       for run_id in "${run_ids[@]}"
       do
       echo "Deleting Run ID $run_id"
       gh api repos/$org/$repo/actions/runs/$run_id -X DELETE >/dev/null
       done
       done
    
    - name: Dump GitHub context
      if: always()
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
      
    - name: Dump steps context
      if: always()
      run: echo '${{ toJSON(steps) }}'
    
    - name: Dump job context
      if: always()
      run: echo '${{ toJSON(job) }}' | sendmail -t k.poorani02@gmail.com
      
  
  
