# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        username: k.poorani02@gmail.com
        password: Dakanusha@2014
    # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
        to: k.poorani02@gmail.com
    # from email name
        from: k.poorani02@gmail.com
  
