 on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.build.outputs.job_output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.build.outputs.job_output2 }}
